In [4]:
from sklearn.feature_extraction.text import CountVectorizer


# Count Vectorizer

In [9]:
vectorizer = CountVectorizer()
corpus = [
'This is the first document.',
'This is the second second document.',

]

In [10]:
X = vectorizer.fit_transform(corpus)

In [11]:
X

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [12]:
print (X)

  (0, 0)	1
  (0, 1)	1
  (0, 4)	1
  (0, 2)	1
  (0, 5)	1
  (1, 3)	2
  (1, 0)	1
  (1, 4)	1
  (1, 2)	1
  (1, 5)	1


In [13]:
vectorizer.get_feature_names()

['document', 'first', 'is', 'second', 'the', 'this']

In [14]:
X.toarray() 

array([[1, 1, 1, 0, 1, 1],
       [1, 0, 1, 2, 1, 1]], dtype=int64)

In [16]:
vectorizer.vocabulary_.get('This is the first document')

In [18]:
vectorizer.transform(['Something completely new document.']).toarray()

array([[1, 0, 0, 0, 0, 0]])

In [19]:
bigram_vectorizer = CountVectorizer(ngram_range=(1, 2),
                                     token_pattern=r'\b\w+\b', min_df=1)
analyze = bigram_vectorizer.build_analyzer()
analyze('Bi-grams are cool!') == (
     ['bi', 'grams', 'are', 'cool', 'bi grams', 'grams are', 'are cool'])

True

In [20]:
X_2 = bigram_vectorizer.fit_transform(corpus).toarray()

In [21]:
X_2

array([[1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1]], dtype=int64)

In [22]:
feature_index = bigram_vectorizer.vocabulary_.get('is this')

In [23]:
X_2[:, feature_index]  

array([[[1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1]],

       [[1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1]]], dtype=int64)